name: CI
on: [push]
jobs:
  build_test_lint:
    name: Test and lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set Node.js 22.x
        uses: actions/setup-node@v6
        with:
          node-version: 22
      - run: npm ci
      - run: npm run build
      - run: npm run test
      - run: npm run lint