name: CI
on: [push]
jobs:
  build_test_lint:
    name: Test and lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - uses: borales/actions-yarn@v4.2.0
        with:
          cmd: set version 4.9.2
      - uses: borales/actions-yarn@v4.2.0
        with:
          cmd: --version # will run `yarn install` command
      - uses: borales/actions-yarn@v4.2.0
        with:
          cmd: install # will run `yarn install` command
      - uses: borales/actions-yarn@v4.2.0
        with:
          cmd: build # will run `yarn build` command
      - uses: borales/actions-yarn@v4.2.0
        with:
          cmd: test # will run `yarn test` command
      - uses: borales/actions-yarn@v4.2.0
        with:
          cmd: lint # will run `yarn lint` command