# Cloned from https://github.com/TileDB-Inc/tiledb-quarto-template

name: Render and deploy Quarto files
on:
  pull_request:

jobs:
  quarto-render-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: "Install Quarto"
      uses: quarto-dev/quarto-actions/install-quarto@v1
      with:
        version: 0.9.141

    - name: "Install yarn dependencies"
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        registry-url: 'https://registry.npmjs.org'
    # Enable corepack to have yarn v3
    - run: corepack enable
    # Verify that yarn 3.x is used
    - run: echo Using yarn version $(yarn --version)
    # Install dependencies and build
    - run: yarn install
    - run: yarn build
      
    - name: "Quarto render"
      shell: bash
      run: |
        quarto render ./quarto/ --fail-if-warnings
        # https://github.com/quarto-dev/quarto-cli/issues/493

    - name: "Deploy to gh-pages"
      uses: peaceiris/actions-gh-pages@v3
      # Change to the name of your repo's primary branch name:
      with:
        # This is GitHub Actions magic; no secrets for us to manage; and this works first-time
        # without any extra configs other than visiting Settings -> Pages in your GitHub repo.
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: quarto/docs
        destination_dir: docs
