name: Publish Packages to npm registry
on:
  release:
    types: [created]
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v5
      - name: Set Node.js 22.x
        uses: actions/setup-node@v6
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm run build
      # Publish packages
      - run: ./scripts/publish.sh common && ./scripts/publish.sh components && ./scripts/publish.sh core && ./scripts/publish.sh react
